[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.project_name }}"
version = "{{ cookiecutter.initial_version }}"
authors = [{name="{{ cookiecutter.author_name }}", email="{{ cookiecutter.author_email }}" }]
description = "{{ cookiecutter.description }}"
readme = "README.md"
license = "MIT"
license-files = [
    "LICENSE",
]
# TODO: Add your dependencies here:
dependencies = ["ilastik-core", "typing_extensions"]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = ["pytest", "ilastik-core"]

[tool.setuptools]
packages = ["{{ cookiecutter.project_name }}"]

[project.entry-points."ilastik.objectfeature_plugins"]
"{{ cookiecutter.project_name }}" = "{{ cookiecutter.project_name }}.{{ cookiecutter.module_name }}:{{ cookiecutter.feature_class_name }}"